# receivers working correctly 
receivers:
  otlp:
    protocols:
      grpc:
      http:
        
processors:
  batch:
    send_batch_size: 1024
    timeout: 5s

  tail_sampling:
    decision_wait: 1s
    num_traces: 10
    expected_new_traces_per_sec: 100
    policies:
      [
        {
          name: test-policy-1,
          type: rate_limiting,
          Rate_limiting: {spans_per_second: 35}
        }
      ]

  memory_limiter:
    limit_mib: 1500
    spike_limit_mib: 512
    check_interval: 5s

extensions:
  health_check: {}
  oauth2client:
    client_id: ef394baf-4541-45c1-975d-4a75d397bb25
    client_secret: Emt7Q~~ixOxKCudfhlUTfez2aYlrK_SAuv8hS
    token_url: https://login.microsoftonline.com/8ac76c91-e7f1-41ff-a89c-3553b2da2c17/oauth2/v2.0/token
    scopes: ["api://ef394baf-4541-45c1-975d-4a75d397bb25/.default"]
  
exporters:
  otlphttp:
    endpoint: https://marcos-appsvc-mdbh-dev-1.azurewebsites.net
    # tls:
      # ca_file: ca-cert.pfx
    auth:
      authenticator: oauth2client

  logging:
    loglevel: debug

service:
  extensions: [oauth2client, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, tail_sampling, memory_limiter]
      exporters: [otlphttp]